// <auto-generated />
using <OWNER_HANDLE>_ERC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

***REMOVED***nullable disable

namespace <OWNER_HANDLE>_ERC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805150724_DropApplicationForms")]
    partial class DropApplicationForms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
***REMOVED***pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

***REMOVED***pragma warning restore 612, 618
        }
    }
}
